import { Product } from "@/types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "রাজশাহীর প্রিমিয়াম হিমসাগর আম (১ম গ্রেড)",
    price: 180,
    originalPrice: 220,
    unit: "প্রতি কেজি",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDW6Qg2GmafB81MfxFKDgBxAcNQP1eXs4DpJjYbtW9wD5E0kI68NB1LzT0F0roT1tEowIG28I-FZfrPcHrzUJmoI0XYdtE5Ab7xDcDIM_rrxSJDz2dkfrsGBc9rAXVWzbI4sQlcXhEZTKnmqO1mQ4jfTzoYXSyxgp5z5f1DFphCvHPPFF9dgKaUA8mK90wQ5kslUaRYlUQkXDYN-bZJUUjd_uHOO1x86CzrtECaHn2VMhkKRHpxaggG",
    stock: 100,
    is_active: true,
    category: "আমের মৌসুম",
    badge: "বেস্টসেলার",
    discountBadge: "১৮% ছাড়",
    origin: "রাজশাহী সদর বাগান",
    description: "আঁশহীন, মিষ্টি সুবাস ও খাঁটি স্বাদের গ্যারান্টি।",
  },
  {
    id: "prod-2",
    name: "দিনাজপুরের রসালো বেদানা লিচু",
    price: 450,
    originalPrice: 520,
    unit: "১০০ পিস",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBI3M3UmGQ1W_KND9DRU4o2RGYQ4Jj7ZgcXIQB2bs_ADT6EcdzhI85pCfsR3Zl5wd44GZjfUoTji1irZslCNodYM9uyYxew6wn3ZVJzwxLOow9Yux8b9Wa6bkpss3oo_CdWuDJv-u-acqqlnBUzr0pC2yPFDmVB9hUVUhV-bvoHAQ51A0DQy_WxEgawSBam_L7B-0OFMmhKiUO1LaLXsepxMspDarzLRIxWRsr0anpGltldNhguxF0L",
    stock: 80,
    is_active: true,
    category: "আমের মৌসুম",
    badge: "জনপ্রিয়",
    discountBadge: "১৪% ছাড়",
    origin: "দিনাজপুর বাগান",
    description: "ছোট বিচি, ভরপুর মিষ্টি রস ও অসাধারণ সুবাস।",
  },
  {
    id: "prod-3",
    name: "মিষ্টি রয়াল গালা আপেল",
    price: 280,
    originalPrice: 320,
    unit: "প্রতি কেজি",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuD7vvDnuUt1ocWXeadCKPdAk6bzsRxpLYQ3LytdLJcyE_KZEBX5zn5tSbgSmk-O5sLpqwLVfTF4hMIjMUi5gFVSyQBtEy8ojNU59WcDFY-tUuOhvFsyl34vKaTnuBRu2CZIzjlzloLxw_GEjkBSEr4P0-NJTOg_hfSTuqh1P0_wdXeX3NtW9x5xm5uMVQsVL8ktsFCLjw4AXbd78lUCxqLEQoIQQRzn2i2EwDl1FRv_tbUFkzcb2qIQ",
    stock: 120,
    is_active: true,
    category: "আমদানি ফল",
    badge: "তাজা আমদানি",
    discountBadge: "১২% ছাড়",
    origin: "নিউজিল্যান্ড গ্রেড-এ",
    description: "মোম ও কেমিক্যাল মুক্ত ক্রিস্পি ও রসালো আপেল।",
  },
  {
    id: "prod-4",
    name: "জুসি মিশরীয় ভ্যালেন্সিয়া মাল্টা",
    price: 230,
    originalPrice: 250,
    unit: "প্রতি কেজি",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDXESbsU73VVTRpHZpxMli7liOzYOXGfZ-gr5O7pzpquvWEusTHkbbvzZtHv6pF3Xw9WX0u93COESDhVqSrzxow8knzndl0YVnogWObc0N1h4B33eZR6zw0PmX7fGP-WaWyhvlStwf9zmj-_tH5DAE-YXDpmPJjhNn3zjN2JfAsqd77bwj8Rs4ifwZLAhw4bqlgKfHTYOAOk1ENMlsSwkWdUiRJSiH39OHh95qYHmKnrctFQiMbCTOG",
    stock: 90,
    is_active: true,
    category: "আমদানি ফল",
    discountBadge: "৮% ছাড়",
    origin: "মিশরীয় আমদানি",
    description: "রসালো ও ভিটামিন-সি সমৃদ্ধ মিষ্টি মাল্টা।",
  },
  {
    id: "prod-5",
    name: "লাল জাম্বো ডালিম / বেদানা",
    price: 390,
    originalPrice: 450,
    unit: "প্রতি কেজি",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDOYeyxRD8v5aIERxxopqRA8tAsEZB1zr6ejQyDSqUYhRxet2LS67KzKSdtbPxWQkl79LgSDaMWmG5RHFyaaF1C014CaGUP6KZAEWW1gwzoZcHtFBMTZHkU7I2Kr6BwenT89jEZ0TP_zTInYTB1QJqPitGcOLwNgIgcY0QTF8REPNY1VraNmYt02WdIuapEEGWLLUAqfiV69ixfm-lqLQbYZqmfBYTbIBoe_LyaWr4b3kkyIrCBLg70",
    stock: 70,
    is_active: true,
    category: "আমদানি ফল",
    badge: "সুপার টেস্ট",
    discountBadge: "১৩% ছাড়",
    origin: "ভারত (ভগওয়া জাত)",
    description: "নরম দানা, গাঢ় লাল ও অত্যন্ত সুমিষ্ট রস।",
  },
  {
    id: "prod-6",
    name: "থাই জাম্বো মিষ্টি পেয়ারা",
    price: 100,
    originalPrice: 120,
    unit: "প্রতি কেজি",
    image_url:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCxdgWiC7OgwBHgVtIwT7ndw_wODYvWJv1SihhPkJg6BfnS9JTBpdIxgvlEMsAzRXuJRVpDZtq8699vKa86W4uv0Y3Um_WpIZt94gLEtIYz5SsLJ6u5WqGgv2CD_kIPQzXUKz1bq9Is78nf0FDCz4stj-FNz-6wtwDIafodgyQry5OZbgr0ItUrsC1mSMOh0YKRNra1iIhRyGaLOXc4-lTwGF6Qa8ykFgkr5TblN0_9ccgmYU4j9oV1",
    stock: 150,
    is_active: true,
    category: "মৌসুমি ফল",
    badge: "বাগান থেকে বাছাই",
    origin: "বরিশালের স্বরূপকাঠি",
    description: "মুচমুচে ক্রিস্পি, মিষ্টি ও শতভাগ পোকা মুক্ত।",
  },
];
