import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00210f",
        "background": "#f1fcf1",
        "surface-container-high": "#e0ebe0",
        "on-surface-variant": "#414942",
        "primary-container": "#154d2e",
        "surface-tint": "#336947",
        "surface-container": "#e5f1e5",
        "outline": "#717971",
        "on-tertiary-container": "#ff946b",
        "primary-fixed-dim": "#9ad4aa",
        "on-tertiary-fixed": "#380d00",
        "surface-container-highest": "#dae6da",
        "inverse-surface": "#29332b",
        "inverse-on-surface": "#e8f4e8",
        "surface-bright": "#f1fcf1",
        "tertiary-fixed-dim": "#ffb59a",
        "on-secondary-fixed": "#002204",
        "secondary-container": "#a0f399",
        "on-surface": "#141e17",
        "on-secondary-container": "#217128",
        "primary": "#00351b",
        "secondary": "#1b6d24",
        "secondary-fixed": "#a3f69c",
        "on-primary-container": "#85bd95",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#551900",
        "on-secondary": "#ffffff",
        "surface-dim": "#d1ddd2",
        "secondary-fixed-dim": "#88d982",
        "outline-variant": "#c0c9bf",
        "inverse-primary": "#9ad4aa",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#005312",
        "on-error-container": "#93000a",
        "surface": "#f1fcf1",
        "on-tertiary-fixed-variant": "#802a00",
        "surface-variant": "#dae6da",
        "on-background": "#141e17",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#b6f0c5",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-container": "#7b2700",
        "on-primary-fixed-variant": "#195031",
        "surface-container-low": "#ebf7eb",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "0.75rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "unit-3xl": "4rem",
        "unit-xl": "2rem",
        "container-max": "1200px",
        "gutter-mobile": "1rem",
        "unit-sm": "0.75rem",
        "gutter-desktop": "1.5rem",
        "unit-md": "1rem",
        "unit-lg": "1.5rem",
        "unit-2xs": "0.25rem",
        "unit-xs": "0.5rem",
        "unit-2xl": "3rem",
      },
      fontFamily: {
        "label-lg": ["Inter", "Noto Sans Bengali", "sans-serif"],
        "body-md": ["Inter", "Noto Sans Bengali", "sans-serif"],
        "display-hero-mobile": ["Noto Sans Bengali", "Noto Sans", "sans-serif"],
        "headline-md": ["Noto Sans Bengali", "Noto Sans", "sans-serif"],
        "body-lg": ["Inter", "Noto Sans Bengali", "sans-serif"],
        "display-hero": ["Noto Sans Bengali", "Noto Sans", "sans-serif"],
        "label-md": ["Inter", "Noto Sans Bengali", "sans-serif"],
        "headline-lg-mobile": ["Noto Sans Bengali", "Noto Sans", "sans-serif"],
        "headline-lg": ["Noto Sans Bengali", "Noto Sans", "sans-serif"],
        "headline-sm": ["Noto Sans Bengali", "Noto Sans", "sans-serif"],
        "body-sm": ["Inter", "Noto Sans Bengali", "sans-serif"],
        "label-sm": ["Inter", "Noto Sans Bengali", "sans-serif"],
      },
      fontSize: {
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0", fontWeight: "400" }],
        "display-hero-mobile": ["28px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0", fontWeight: "400" }],
        "display-hero": ["40px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "30px", letterSpacing: "0", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "0", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
